### PR TITLE
Using cmake ninja and forked clang

### PR DESCRIPTION
**Pull request by 4c0n**
Need to reduce size even further and add proper cleanup. But for now it works and the size isn't as humongous as it was when I started.

### CODE REVIEW

**Comment by marbub** [comment]
Any progress so far?

**Comment by 4c0n** [comment]
@marbub You can see it here. I've had other priorities lately, but will likely continue this when everything settles down a little again.
Currently it works, but the size is still big (~7.5GB), haven't really looked into what artifacts make it that big.
You can always try/test it by using the command that @flathubbot commented.

**Comment by marbub** [comment]
You can see in the [LLVM build documentation](https://llvm.org/docs/CMake.html#llvm-specific-variables) that you can disable nearly everything. You need libClang and libFormat.

**Comment by 4c0n** [comment]
@marbub If you're not going to make concrete/helpful suggestions, I suggest you keep those comments to yourself. You've already started this discussion with me in the previous PR (https://github.com/flathub/flathub/pull/1941) and also refused to cooperate. As you can see and as I've told you already I have read the documentation and am using the build flags already. When I asked you, you basically said that you don't work on/with it anymore, so you don't know how to do it either and are also not willing to help out.

I'm doing this out of my own personal interest and am not getting paid by anyone to do this, so it'll happen at my pace, feel free to help out/try it yourself if you want to make it happen sooner. But please stop globally referring to the documentation. If anything spend your time on triggering someone at the Qt project to improve the build instructions of the fork so that it's actually clear how the fork is supposed to be used. Or even better get the patches merged into the upstream so that the forks aren't needed and we can just use the mainline version.

Or don't... but then don't expect any response from me anymore.

**Comment by marbub** [comment]
@4c0n [https://code.qt.io/cgit/qtsdk/qtsdk.git/tree/packaging-tools/build_clang.py](https://code.qt.io/cgit/qtsdk/qtsdk.git/tree/packaging-tools/build_clang.py)

But I think this will be not very helpful. It is quite complicated and not size optimized. You could use the provided binaries of our libClang distribution but I don't know the policies of flathub. 

The patches will not get upstream because they LLVM guys denied them. They are to specially tailored for our use cases.

I am not paid for that either so it would be nice if you stop telling me that I should do. ;-)

**Comment by 4c0n** [comment]
bot build io.qt.QtCreator

**Comment by 4c0n** [comment]
bot, build io.qt.QtCreator

**Pull request merged**
