### PR TITLE
Beta

### PR DESCRIPTION
**Pull request by 4c0n**
Update beta branch to Qt Creator 6.0.0 Release Candidate 1.

### CODE REVIEW

**Comment by 4c0n** [comment]
bot, build io.qt.QtCreator.yaml

**Comment by 4c0n** [comment]
bot, build io.qt.QtCreator

**Comment by 4c0n** [comment]
@marbub I'm running into some issues here and thought maybe you have an idea on what may be going on.
For some reason currently beyond my understanding CMake seems to be trying to populate googletests. This was not happening in the previous version. I'm suspecting it might have something to do with the google benchmark tool as that will try to install it's own bundled version of googletest, but I might be completely wrong about that. I tried adding googletest and the benchmark tool to the manifest in hopes they would be detected and thus not downloaded (as the build of the manifest runs in sandbox mode and cannot download anything).

Do you have an idea what's going on here? Please see the log of the failed build for more details :)

**Comment by marbub** [comment]
I find it a little bit strange that it is compiled with tests. There is a setting WITH_TESTS which should be disabled. We use Google test from a submodule repository. So there is no need to check that by yourself. But for a release this tests are not needed. So it's better to disable them.

**Comment by marbub** [comment]
I would disable the qmldesigner too because it is now called Design Studio.

**Comment by 4c0n** [comment]
> I find it a little bit strange that it is compiled with tests. There is a setting WITH_TESTS which should be disabled. We use Google test from a submodule repository. So there is no need to check that by yourself. But for a release this tests are not needed. So it's better to disable them.

@marbub It seems to be disabled by default? See: https://github.com/qt-creator/qt-creator/blob/335f85c525bde542c2d6b73f0a402265fc560287/CMakeLists.txt#L32 Is there something I'm missing here?

**Comment by 4c0n** [comment]
> I would disable the qmldesigner too because it is now called Design Studio.

@marbub Okay sounds good, I don't see an option for that in the CMakeLists.txt though, where can I find the option to do that?

**Comment by marbub** [comment]
I would disable the qmldesigner too because it is now called Design Studio.

> > I would disable the qmldesigner too because it is now called Design Studio.
> 
> @marbub Okay sounds good, I don't see an option for that in the CMakeLists.txt though, where can I find the option to do that?

I thought there was an option but I do not work in release management.

**Comment by marbub** [comment]
> > I find it a little bit strange that it is compiled with tests. There is a setting WITH_TESTS which should be disabled. We use Google test from a submodule repository. So there is no need to check that by yourself. But for a release this tests are not needed. So it's better to disable them.
> 
> @marbub It seems to be disabled by default? See: https://github.com/qt-creator/qt-creator/blob/335f85c525bde542c2d6b73f0a402265fc560287/CMakeLists.txt#L32 Is there something I'm missing here?

Because of that I am surprised to see your problems. I am not an expert for cmake,  quite the opposite. But to my knowledge you should not run in your problems if the tests are not build.

**Comment by marbub** [comment]
There is a different variable for the tests. I think it's called BUILD_TESTS. But it's deep into the night here and I will be working again on Monday.

**Comment by 4c0n** [comment]
apparently CMake will assume it is part of the build when the submodule is initialized and exists, why it then still wants to download a release and populate directories in the config stage is beyond me, but for now not initializing the submodules at least allows it to configure a build. Unfortunately it also causes the other submodules to not get configured/build like for example litehtml.
The only other tests related option I could find was: `BUILD_TESTS_BY_DEFAULT` and turning it off did not make a difference.
The qmldesigner plugin can be disabled using the `BUILD_PLUGIN_QMLDESIGNER` option, however I cannot find any info on how to build/include Design Studio, so I'm leaving it enabled for now as otherwise there would not seem to be a good alternative available.

**Comment by marbub** [comment]
Design Studio is it own app. So it is not part of Qt Creator. It should have its own flatpak.

**Comment by marbub** [comment]
Can you open an Jira task and assign it to me, so I can look into the test thingy.

**Comment by 4c0n** [comment]
> Can you open an Jira task and assign it to me, so I can look into the test thingy.
@marbub 
I couldn't assign the issue, but left a comment that you asked to be assigned.
https://bugreports.qt.io/browse/QTCREATORBUG-26626

**Comment by marbub** [comment]
I seem that litehtml  is fetching googletest too.

[This patch](https://codereview.qt-project.org/c/qt-creator/qt-creator/+/383602) should fix it.

**Comment by 4c0n** [comment]
> I seem that litehtml is fetching googletest too.
> 
> [This patch](https://codereview.qt-project.org/c/qt-creator/qt-creator/+/383602) should fix it.

Right, that makes sense. I reviewed the patch.

**Pull request closed without merging**
